management:
  security:
    enabled: true
server:
  ssl:
    keystore: classpath:keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: demokey
    key-password: password
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: test
server:
  port: 8000
